### ISSUE TITLE
Can not set "updated" field for atom feed

### ISSUE THREAD

**Issue by thkoch2001** [jaspervdj/hakyll#937] opened 2022-05-02 08:15 UTC
My blog is syndicated on some planet. Every time I post a new item, all my old posts end up on top of the planet since the "updated" field of each item is set to the compile time of the blog.

I tried setting the metadata fields "updated", "date" or "published" to the value "2014-02-05T00:00:00Z" without any effect.

I'm using hakyll version 4.13.4.0 from Debian testing but it seems the relevant code has not been touched since at least this version.

**Comment by Minoru** [comment] 2022-05-09 15:59
I can't reproduce this with Hakyll 4.15.1.1 revision 1 (from Stackage LTS 19.0) and [my blog](https://github.com/Minoru/blog.debiania.in.ua/tree/62139cd950f7c9e4b230bfb33d6c5c92186ed67a). For me, everything works as expected:
- without adding anything to the front matter, Hakyll pulls the date from the path;
- with `published: 2021-07-27T00:00:00Z` in the front matter, I see the post's `<published>` and `<updated>` tags use the specified date and time;
- with `updated: 2021-07-27T00:00:00Z`, `<published>` uses the date from the path while `<updated>` uses the specified date.

Are you sure you are not overriding `published` and/or `updated` anywhere in your code, e.g. by stacking a `Context` in the wrong order? Can you point me to the source code of your site, or better yet, a minimal reproducible example of the problem?

**Comment by Minoru** [comment] 2022-05-31 20:41
@thkoch2001, did you manage to get to the bottom of this?

**Comment by Minoru** [comment] 2022-08-30 18:00
@thkoch2001, ping.

**Comment by Minoru** [comment] 2022-11-04 18:54
@thkoch2001, ping.

**Comment by Minoru** [comment] 2022-12-11 14:40
Closing because I can't reproduce and the issue author doesn't respond.

**Closed by Minoru** 2022-12-11 14:40 UTC
Labels: bug
