### ISSUE TITLE
hakyll tutorial stack build failed.

### ISSUE THREAD

**Issue by Franceshe** [jaspervdj/hakyll#739] opened 2019-11-17 21:17 UTC
Hi, guys, I had a problem while following the hakyll installation tutorial:
https://jaspervdj.be/hakyll/tutorials/01-installation.html
when I try to execute
`
 stack build
`
It pops up error message as:
```
➜  my-site stack build
Error parsing targets: The specified targets matched no packages.
Perhaps you need to run 'stack init'?
```
There's a related issue-https://github.com/commercialhaskell/stack/issues/4531
But it does not help since my ghc compiler is already the latest version.

Can you guys help? Thanks!

**Comment by dunnl** [comment] 2019-11-18 20:47
Just to be clear, did you run `stack init`?

**Comment by Franceshe** [comment] 2019-11-18 21:57
> Just to be clear, did you run `stack init`?

Thanks. It looks like I had omitted a error message after running `stack init`, it shows following:


`$stack init
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- ./
- state-machine-testing/

Selecting the best among 16 snapshots...

* Partially matches lts-14.14
    hakyll not found
        - my-site requires ==4.13.*
.
.
.
.
* Partially matches lts-0.7
    hakyll not found
        - my-site requires ==4.13.*

Selected resolver: lts-14.14
*** Resolver lts-14.14 will need external packages:
    hakyll not found
        - my-site requires ==4.13.*

*** Omitting packages with unsatisfied dependencies
*** Ignoring package: my-site
Initialising configuration using resolver: lts-14.14
Total number of user packages considered: 2
Warning! Ignoring 1 packages due to dependency conflicts:
        - my-site.cabal

Writing configuration to file: stack.yaml
All done.`
And then I try to omit by add the the resolver by running
`$stack init --omit-packages` 
But still failed the command 
`$ stack exec site build

Warning (added by new or init): Some packages were found to be incompatible with the resolver and have been left commented out in the packages section.
You can omit this message by removing it from stack.yaml

Executable named site not found on path: ["/Users/project/Winter2019/blog_build_package/hakyll/my-site/.stack-work/install/x86_64-osx/6c5262d1f3b7bb9ac7564d6db8eecc6bf678bed20129f7adcc0ece7cdcc6aea2/8.6.5/bin","/Users/.stack/snapshots/x86_64-osx/6c5262d1f3b7bb9ac7564d6db8eecc6bf678bed20129f7adcc0ece7cdcc6aea2/8.6.5/bin","/Users/.stack/compiler-tools/x86_64-osx/ghc-8.6.5/bin","/Users/.stack/programs/x86_64-osx/ghc-8.6.5/bin","/Users/anaconda3/bin","/Users/.rvm/gems/ruby-2.4.2/bin","/Users/.rvm/gems/ruby-2.4.2@global/bin","/Users/.rvm/rubies/ruby-2.4.2/bin","/Users/anaconda3/bin","/Users/.cargo/bin","/usr/local/bin","/usr/bin","/bin","/usr/sbin","/sbin","/usr/local/go/bin","/opt/X11/bin","/Library/Frameworks/Mono.framework/Versions/Current/Commands","/usr/local/share/npm/bin","/Users/.rvm/bin","/usr/local/share/npm/bin"]`

So from this error message i have several concerns:
1.How can i removing this message from stack.yaml 
2. why the not found path message had pops out since i already set path in my
~/.zshrc as `export PATH="$PATH:/Users/siyunhe/.local/bin/hakyll-init"` and sourced it...

Thanks again!

**Comment by dunnl** [comment] 2019-11-18 22:33
The problem is that the most recent version of the Hakyll library is not available on [Stackage](https://www.stackage.org/package/hakyll) (see #730). Stackage maintains snapshots of Haskell libraries that are known to work together, and the snapshot (i.e. the resolver, in your case `lts-14.14`) doesn't have the version that `hakyll init` added as a dependency.
[Hackage](https://hackage.haskell.org/package/hakyll) is another repository of Haskell packages  and you'll see it has a more recent version.
* One workaround is to add these lines
```
extra-deps:
- hakyll-4.13.0.1
```
to `stack.yaml`. This tells stack to use the version from Hackage.
Another workaround is to modify `stack.yaml` to say `resolver: lts-12.26` instead of `resolver: lts-14.14`. I think I would try the **second** option first because it's more likely to continue working in the future.
* The issue isn't that Hakyll isn't in your PATH, it's that stack failed to build the executable (which is just called `site`). It's just another error message from the first problem.

These sorts of issues are not uncommon with Haskell unfortunately. The build systems for Haskell are very sophisticated but also pretty complex.

**Comment by Franceshe** [comment] 2019-11-18 22:57
> The problem is that the most recent version of the Hakyll library is not available on [Stackage](https://www.stackage.org/package/hakyll) (see #730). Stackage maintains snapshots of Haskell libraries that are known to work together, and the snapshot (i.e. the resolver, in your case `lts-14.14`) doesn't have the version that `hakyll init` added as a dependency.
> [Hackage](https://hackage.haskell.org/package/hakyll) is another repository of Haskell packages and you'll see it has a more recent version.
> 
> * One workaround is to add these lines
> 
> ```
> extra-deps:
> - hakyll-4.13.0.1
> ```
> 
> to `stack.yaml`. This tells stack to use the version from Hackage.
> Another workaround is to modify `stack.yaml` to say `resolver: lts-12.26` instead of `resolver: lts-14.14`. I think I would try the **second** option first because it's more likely to continue working in the future.
> 
> * The issue isn't that Hakyll isn't in your PATH, it's that stack failed to build the executable (which is just called `site`). It's just another error message from the first problem.
> 
> These sorts of issues are not uncommon with Haskell unfortunately. The build systems for Haskell are very sophisticated but also pretty complex.

Hi dunnl, thanks for the detailed reply and explanation.
I had tried both resolutions you provided by still get the same error message from 
```
➜  my-site emacs -nw stack.yaml
➜  my-site stack build
Warning (added by new or init): Some packages were found to be incompatible with the resolver and have been left commented out in the packages section.
You can omit this message by removing it from stack.yaml

[1 of 2] Compiling Main             ( /Users/siyunhe/.stack/setup-exe-src/setup-mPHDZzAJ.hs, /Users/siyunhe/.stack/setup-exe-src/setup-mPHDZzAJ.o )
[2 of 2] Compiling StackSetupShim   ( /Users/siyunhe/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /Users/siyunhe/.stack/setup-exe-src/setup-shim-mPHDZzAJ.o )
Linking /Users/siyunhe/.stack/setup-exe-cache/x86_64-osx/tmp-Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.4 ...
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
Building all executables for `state-machine-testing' once. After a successful build of all of them, only specified executables will be rebuilt.
state-machine-testing> configure (lib + exe)
Configuring state-machine-testing-0.1.0.0...
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
state-machine-testing> build (lib + exe)
Preprocessing library for state-machine-testing-0.1.0.0..
Building library for state-machine-testing-0.1.0.0..
[1 of 2] Compiling Lib
[2 of 2] Compiling Paths_state_machine_testing
Preprocessing executable 'state-machine-testing-exe' for state-machine-testing-0.1.0.0..
Building executable 'state-machine-testing-exe' for state-machine-testing-0.1.0.0..
[1 of 2] Compiling Main
[2 of 2] Compiling Paths_state_machine_testing
Linking .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/state-machine-testing-exe/state-machine-testing-exe ...
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
state-machine-testing> copy/register
Installing library in /Users/siyunhe/project/Winter2019/blog_build_package/hakyll/my-site/.stack-work/install/x86_64-osx/7f67790caf5562d80fa70c0b8b99bc71475821eb41bf19cfc264c87570663beb/8.4.4/lib/x86_64-osx-ghc-8.4.4/state-machine-testing-0.1.0.0-4rWCGrD6j1iL28XkmhvIo4
Installing executable state-machine-testing-exe in /Users/siyunhe/project/Winter2019/blog_build_package/hakyll/my-site/.stack-work/install/x86_64-osx/7f67790caf5562d80fa70c0b8b99bc71475821eb41bf19cfc264c87570663beb/8.4.4/bin
Registering library for state-machine-testing-0.1.0.0..
➜  my-site stack exec site build
Warning (added by new or init): Some packages were found to be incompatible with the resolver and have been left commented out in the packages section.
You can omit this message by removing it from stack.yaml

Executable named site not found on path: ["/Users/siyunhe/project/Winter2019/blog_build_package/hakyll/my-site/.stack-work/install/x86_64-osx/7f67790caf5562d80fa70c0b8b99bc71475821eb41bf19cfc264c87570663beb/8.4.4/bin","/Users/siyunhe/.stack/snapshots/x86_64-osx/7f67790caf5562d80fa70c0b8b99bc71475821eb41bf19cfc264c87570663beb/8.4.4/bin","/Users/siyunhe/.stack/compiler-tools/x86_64-osx/ghc-8.4.4/bin","/Users/siyunhe/.stack/programs/x86_64-osx/ghc-8.4.4/bin","/Users/siyunhe/anaconda3/bin","/Users/siyunhe/.rvm/gems/ruby-2.4.2/bin","/Users/siyunhe/.rvm/gems/ruby-2.4.2@global/bin","/Users/siyunhe/.rvm/rubies/ruby-2.4.2/bin","/Users/siyunhe/anaconda3/bin","/Users/siyunhe/.cargo/bin","/usr/local/bin","/usr/bin","/bin","/usr/sbin","/sbin","/usr/local/go/bin","/opt/X11/bin","/Library/Frameworks/Mono.framework/Versions/Current/Commands","/usr/local/share/npm/bin","/Users/siyunhe/.rvm/bin","/usr/local/share/npm/bin"]
```

Some how it throws some new error message which looks like complain about my clang compiler
build in mac ox? 
Yeah, haskell got a very complicated build tool chain which really confused me.

**Comment by dunnl** [comment] 2019-11-19 00:25
The line
```
Installing executable state-machine-testing-exe in /Users/siyunhe/project/Winter2019/blog_build_package/hakyll/my-site/.stack-work/install/x86_64-osx/7f67790caf5562d80fa70c0b8b99bc71475821eb41bf19cfc264c87570663beb/8.4.4/bin
```
looks like your executable is being named `state-machine-testing-exe`. You should have a cabal file listing `site` as the name of your executable. It's being built just fine but it has the wrong name.

The line
```
Warning (added by new or init): Some packages were found to be incompatible with the resolver and have been left commented out in the packages section.
You can omit this message by removing it from stack.yaml
```
sounds like there's an actual line in your file `stack.yaml` and you can simply delete this line from that file. If you're using `lts-12.26` I don't think you'll have incompatible packages, it might be a line that got added for some other reason.

**Comment by armatures** [comment] 2019-11-22 23:24
I was getting a similar `hakyll not found` error, and I couldn't get `stack init` to work. I wrote this `stack.yaml` file to the root of my directory, and `stack build` started working:
```
resolver: lts-14.15
extra-deps:
- hakyll-4.13.0.1
```

**Comment by louwers** [comment] 2020-04-04 11:36
Had the same problem.

**Comment by hvr** [comment] 2020-04-12 12:58
Duplicate of #730

**Closed** 2020-04-14 16:42 UTC
