### ISSUE TITLE
hakyll can't handle unicode?

### ISSUE THREAD

**Issue by davidspies** [jaspervdj/hakyll#614] opened 2018-03-04 17:32 UTC
Trying to build the default (hakyll-init) site I get this:

```
$ stack exec site build
Initialising...
  Creating store...
  Creating provider...
  Running rules...
Checking for out-of-date items
Compiling
  [ERROR] ./about.rst: hGetContents: invalid argument (invalid byte sequence)

```
It looks like it's a problem with the unicode character (it builds when I remove it):
The line:
`1. Amamus Unicode 碁`

Hakyll and site built with `nix` and `stack --resolver=lts-10.7`

**Comment by cbzehner** [comment] 2018-03-04 19:47
I don't think Unicode is the root cause here. I have built [Unicode pages](http://www.cbzehner.com/posts/1970-01-01-security-tips.html) successfully with Hakyll.

Could you [check the encoding](https://unix.stackexchange.com/questions/11602/how-can-i-test-the-encoding-of-a-text-file-is-it-valid-and-what-is-it) of your `about.rst` file? It might be in some other encoding like [Big5](https://en.wikipedia.org/wiki/Big5)?

**Comment by jaspervdj** [comment] 2018-03-04 20:03
This is a `readFile` exception that most commonly pops up if your system locale is set to something like ISO 8859-1 rather than UTF-8.  On Linux this usually means that `LANG` / `LC_ALL` is set incorrectly.

**Comment by davidspies** [comment] 2018-03-04 21:41
```
$ file -i about.rst 
about.rst: text/plain; charset=utf-8

```

**Comment by davidspies** [comment] 2018-03-04 21:45
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

```

However I built with `nix` so maybe it wipes that out?

**Comment by davidspies** [comment] 2018-03-04 21:52
Oh, yeah:
$ stack --nix exec -- locale
```
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

```

Any idea how to deal with that?

**Comment by jaspervdj** [comment] 2018-03-05 16:50
I'm not very experienced with Nix but just googling for "nix lang lc_all" led me to https://github.com/NixOS/nix/issues/318 which provides a solution near the bottom of the thread.  Closing the issue as it's not really related to Hakyll.

**Closed by jaspervdj** 2018-03-05 16:50 UTC

**Comment by dunnl** [comment] 2018-07-22 16:16
To be explicit (since I've still been wresting with this) it seems that the Prelude read/write methods (e.g. `writeFile`) in a Nix environment require both `LANG` and `LOCALE_ARCHIVE` set (the latter being a nixpkgs-specific variable stemming from a patch in glibc). Presently I don't think you can run Hakyll in a Nix build without explicitly passing both.

**Comment by dunnl** [comment] 2018-08-08 19:16
The problem is that operations like `hGetContents` require information about the locale settings and generated locale files. It's not super clear from the other thread, but in the Nix world this means having something like `LOCALE_ARCHIVE = "${pkgs.glibcLocales}/lib/locale/locale-archive"` in the environment, besides the regular `LC` / `LANG` variables.

`LOCALE_ARCHIVE` is a Nixpkgs-specific patch to glibc so that the locale archive can be stored in `/nix/store`, see [this patch](https://github.com/NixOS/nixpkgs/blob/27c6bf0ef377e79b57e9037f7750586e4603fe37/pkgs/development/libraries/glibc/nix-locale-archive.patch). For a real example see [this blog post](http://www.cs.yale.edu/homes/lucas.paul/posts/2017-04-10-hakyll-on-nix.html). Note that you do not need to put `export` statements in your builder script like the author does; it suffices to pass the above definition as an attribute in the mkDerivation parameters.

That's why `pure:false` works: `LOCALE_ARCHIVE` is set in your regular environment when you install Nix or run NixOS.

Some of this isn't *exquisitely* well-documented right now, unfortunately.

**Comment by teto** [comment] 2018-08-09 02:41
Thanks for the precision. I knew what is --pure was but was just surprised that this was the default for stack as even on nix, it's not advertised much. There must be a good reason for it.

**Comment by koijigen** [comment] 2022-07-17 05:14
Today, met this error on Windows.
And I fixed it.
I'll write it down for those who have arrived by googling 👀 

I use Japanese as system locale.
So I did bellow to fix this error :

1. execute command `chcp 65001`
2. run `site rebuild`

Note : To change system locale by `chcp` is temporary.
