### ISSUE TITLE
stack install hakyll doesn't work

### ISSUE THREAD

**Issue by Juev** [jaspervdj/hakyll#498] opened 2016-12-19 15:38 UTC
When I tried to install hakyll with command:
```
stack install hakyll
```
I get errors:
```
$ stack install hakyll

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for hakyll-4.9.2.0:
    http-conduit-2.1.11 must match >=2.2 && <2.3 (latest applicable is 2.2.3)

Plan construction failed.
```

I found solution with command:
```
$ stack --resolver=nightly-2016-10-31 install hakyll
```

**Comment by jaspervdj** [comment] 2016-12-19 16:04
Duplicate of #475

**Closed by jaspervdj** 2016-12-19 16:04 UTC
