### ISSUE TITLE
Attempting to build site while `watch` is active fails with unhelpful error

### ISSUE THREAD

**Issue by othercriteria** [jaspervdj/hakyll#336] opened 2015-03-05 09:13 UTC
After successfully running a local preview of a site through `./Main watch` (I renamed `Main` to `site` in the snippet below), I tried building the site from a different shell session in the same directory and got the following output:

```
ghc --make site -optl -w -dynamic -O2
[1 of 1] Compiling Main             ( site.hs, site.o )
Linking site ...
[SNIP]
./site rebuild
Removing _site...
Removing _cache...
Removing _cache/tmp...
Initialising...
  Creating store...
  Creating provider...
site: Data.Binary.Get.runGet at position 32749: demandInput: not enough bytes
make: *** [_site] Error 1
```

I did this accidentally, not remembering that the preview was still running. An error message like "instance already running" would make this easier to interpret and might catch the problem before it crashes and burns and does stuff to _site files.

**Comment by rasendubi** [comment] 2016-04-15 08:51
I'm unable to reproduce the issue with hakyll-4.7. I also tried a bit worse case and ran two `./site watch` simultaneously -- that worked fine, and I got not error.

@othercriteria, is that still an issue?

**Comment by jaspervdj** [comment] 2016-04-15 09:46
I still think this can occur as a (maybe rare) race condition if you run two `./site watch` processes in the same directory. I think this should be easily fixed by adding a `_cache/hakyll.pid` file. Hakyll would then refuse to run if this file exists.

**Comment by jtojnar** [comment] 2016-06-22 21:16
I just received this error after upgrading to 4.8, I only ran one instance of `site watch` though.

**Comment by jtojnar** [comment] 2016-06-25 00:23
It seems that in my case the issue occurred when I terminated the script during `Creating provider...` phase (e.g. by SIGINT).

**Comment by jaspervdj** [comment] 2016-06-25 11:34
That sounds like a different issue: you probably killed it while it was writing to the cache, and then you ended up with an bad cache file.

**Closed** 2016-07-23 10:05 UTC
