### ISSUE TITLE
hakyll is currently broken in Nixpkgs

### ISSUE THREAD

**Issue by markus1189** [jaspervdj/hakyll#833] opened 2021-03-01 15:44 UTC
Hey :wave:,

unfortunately, `hakyll` is currently marked broken in `nixpkgs`, because it requires `pandoc >= 2.10 && <= 2.11`.

I saw that this restriction is already lifted with #826, but there was no release since then.

Do you plan to make a new release soon?  I would prefer that over patching it manually inside nixpkgs, as it builds fine with pandoc 2.11 for me :grin:

**Comment by Minoru** [comment] 2021-03-04 23:20
@jaspervdj Looks like a new release could resolve both this and #832, can you publish it please?

**Comment by jaspervdj** [comment] 2021-03-14 12:38
@Minoru Yes, I can do a release, but should we revert #810 first until we can fix it?

**Comment by Minoru** [comment] 2021-03-14 12:45
@jaspervdj Yes, this was on my TODO list for today :) Since you're making commits anyway, please revert it, and I'll go update the relevant issue and explain the situation to Gwern. Sounds okay?

**Comment by jaspervdj** [comment] 2021-03-14 12:55
Sounds good!  Released as `v4.14.0.0`.

**Comment by Minoru** [comment] 2021-03-14 13:07
Thanks! I think this issue can be closed now.

**Closed by Minoru** 2021-03-14 13:07 UTC

**Comment by ezzieyguywuf** [comment] 2021-03-14 14:54
> Closed #833 <https://github.com/jaspervdj/hakyll/issues/833>.
>

<3

>

**Comment by YellowOnion** [comment] 2021-06-02 06:06
Did anyone fix this in nixpkgs, it's still broken for me? Should I open a bug report in nixpkgs?

**Comment by Minoru** [comment] 2021-06-02 19:22
@YellowOnion It's not marked as broken in https://raw.githubusercontent.com/vaibhavsagar/nixpkgs/master/pkgs/development/haskell-modules/hackage-packages.nix (sorry I can't link to a line — GitHub doesn't display files this big), so what you're experiencing is probably a different issue. If you believe it's a problem with Hakyll itself, submit a new issue here; if you think it's more likely to be a problem with nixpkgs, please submit an issue to them.

**Comment by YellowOnion** [comment] 2021-06-03 01:38
Sorry I should have been more specific, it's broken in unstable.

https://raw.githubusercontent.com/NixOS/nixpkgs/nixos-unstable/pkgs/development/haskell-modules/hackage-packages.nix

**Comment by Minoru** [comment] 2021-06-03 12:57
@YellowOnion Looks like it was marked broken in https://github.com/NixOS/nixpkgs/pull/122286. There's a long discussion there, but Hakyll is never mentioned.

I don't know what *exactly* breaks Hakyll on NixOS, so I can't help you here. You got to figure out the reason somehow (does nix show any errors?), and decide whom to report it to.

**Comment by YellowOnion** [comment] 2021-06-04 03:23
I get some errors about missing dependencies (cryptonite etc) which doesn't make a lot of sense if dependencies are handled properly. Honestly I might move back to 21.05 since Gnome 40 is giving me issues anyway. And I got Hakyll working with stack in the meantime.

**Comment by rpearce** [comment] 2021-06-06 03:35
I don't believe nixpkgs hangs on to every version of every haskell package (it typically might be the latest?), so the upper bounds on many haskell packages create problems.

While I've previously used the `callHackage` helper to override certain package versions (https://github.com/rpearce/hakyll-nix-template/blob/main/generator/hpkgs.nix#L25-L28), that pattern is no longer working with the latest `cryptonite` issues. Using that pattern, I get some really fun infinite recursion that is seemingly a dead-end.

I'm currently working on putting together a better [`hakyll-nix-template`](https://github.com/rpearce/hakyll-nix-template/) that will leverage nix flakes and _hopefully_ make it so we can have 99% reproducibility without these headaches.
