### ISSUE TITLE
Italics being replaced with emphasized and attribues are stripped out

### ISSUE THREAD

**Issue by decapo01** [jaspervdj/hakyll#825] opened 2020-12-03 01:56 UTC
I'm attempting to use font awesome with hakyll and the recommended tag from font awesome looks like this
```
<i class="fa fa-map-marker" aria-hidden="true"></i>
```
however hakyll only renders
```
<em></em>
```
In it's place

**Comment by decapo01** [comment] 2020-12-03 02:04
If anyone else encounters this, a workaround is to use font awesome with the `span` tag

**Comment by Minoru** [comment] 2020-12-03 19:51
Hi! I couldn't reproduce this with Hakyll 4.13.4.0 (Stackage LTS 16.21). I inserted the `<i>` tag you provided into both a template and a Markdown source, and both were copied into the HTML output unmodified.

What Hakyll version are you running? Where are you inserting this HTML? Can you provide a small example of a complete Hakyll site that I can simply build on my machine and play with?

**Comment by decapo01** [comment] 2020-12-04 02:19
I'm on lts 14.16 and it appears that my hakyll version is 4.13.0.1.  I updated to your specs (Hakyll 4.14.4.0, LTS 16.21) and I'm getting the same results.  I'll try to get a complete hakyll site up for you to look at to see what's happening in the pretty soon.  I would also like to note that I'm currently on a mac.

**Comment by decapo01** [comment] 2020-12-04 05:28
Ok I was able to reproduce and made a repo for this here https://github.com/decapo01/hakyll-bug-example.  The specific error is occurring here  https://github.com/decapo01/hakyll-bug-example/blob/master/blah.html#L8.  It actually works in the default.html template, however if I make a sub view the `<i>` tag is replaced with `<em>` and the attributes are removed.

**Comment by Minoru** [comment] 2020-12-04 14:52
Thanks! It looks like this is just how Pandoc parses things:

```
$ pandoc -f html -t native blah.html 
[Para [Str "---",SoftBreak,Str "title:",Space,Str "Contact",SoftBreak,Str "---"]
,Header 1 ("blah",[],[]) [Str "Blah"]
,Div ("",["my-class"],[])
 [Header 3 ("there-should-be-a-map-marker-under-me",[],[]) [Str "There",Space,Str "should",Space,Str "be",Space,Str "a",Space,Str "map",Space,Str "marker",Space,Str "under",Space,Str "me"]
 ,Plain [Emph []]]]
```

I traced it down to [this line in Pandoc's HTML parser](https://github.com/jgm/pandoc/blob/7199d68ba078148ff76a38f2c483da73edd62747/src/Text/Pandoc/Readers/HTML.hs#L586), and looking at `git blame`, it appears that it has been this way ever since Pandoc's inception.

I have hard time telling if it's a bug or not; looks like Pandoc deliberately coalesces tags into "semantic entities" like `Emph`, but I might be wrong. Their bug tracker has a couple issues about Markdown-to-HTML conversion and whether `*this*` should turn into `<i>` or `<em>`, but nothing on *reading* these things from HTML. I also didn't find anything relevant on their mailing list.

Since the problem stems from Pandoc, I think you should ask on [their help forums](https://pandoc.org/help.html) instead, and I'll close this issue. Thanks for filing it though, and for providing a workaround!

**Closed by Minoru** 2020-12-04 14:52 UTC
Labels: bug, question
